export const sampleCases = [
  {
    id: "689b491341038c43f3b2a5d2",
    caseNumber: "BS304776",
    vehicle: {
      vehicleLicenseNumber: "DL39621",
      brandName: "TOYOTA",
      model: "COROLLA",
      firstRegistered: "2006-06-21T00:00:00Z",
      vehicleType: "PERSONBIL",
      vin: "NMTBZ20E70R135476",
      color: null,
      vehicleGroupType: null,
      isCommercialVan: false,
      vehicleGroupTypeName: null,
    },
    legalOwner: {
      name: "QUYNH LE LE",
      phoneNumber: "98829672",
      address: "Skarpsnoveien 3 B",
      postalCode: "3055",
      postalArea: "KROKSTADELVA",
      email: "quynh.le@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    caseWorker: {
      name: "API-Riis- Montasje",
      id: "656859a4ff02e9b608c6cdd5",
      organizationName: "RIIS BILGLASS",
      caseWorkerRole: "Workshop",
    },
    status: "InvoiceControl",
    dateOfIncident: "2025-07-30T00:00:00Z",
    jobExecutionDate: null,
    placeOfIncident: "E 18",
    cause: "Steinsprut",
    mileage: 219951,
    mileageUnit: "km",
    jobType: "Repair",
    multipleGlasses: [],
    contactPerson: null,
    contact: {
      name: "Le Quynh Le",
      phoneNumber: "98829672",
      address: null,
      postalCode: null,
      postalArea: null,
      email: "quynh.le@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    requiresVAT: false,
    registrationDate: "2025-08-12T14:00:51.966Z",
    caseDeductible: 0,
    caseDeductibleCurrency: "NOK",
    deductiblePercentage: 0,
    isDeductiblePercentage: false,
    minDeductible: 0,
    workshop: {
      name: "Riis Bilglass Drammen Rundtom",
      organizationNumber: "987761792",
      organizationId: "641cc1568a43f5dc22fed98c",
      organizationMembership: {
        organizationNumber: "921 979 436",
        organizationId: "5a4361e6853af600010f141b",
        name: "RIIS BILGLASS",
        organizationType: "Organization",
      },
    },
    insuranceInformation: {
      id: null,
      insuranceOwner: {
        name: "Ngoi van Vu",
        phoneNumber: "100967802",
        address: null,
        postalCode: null,
        postalArea: null,
        email: "ngoi.vu@email.com",
        organizationNumber: null,
        externalReference: null,
      },
      insuranceProvider: {
        id: "648b1fc6eef6a66f28bd8747",
        name: "WATERCIRCLES FORSIKRING",
        organizationNumber: "915 495 486",
        key: "WATERCIRCLES",
        settings: null,
        coverageResponseId: 35,
        status: "Enabled",
        universalId: "startid:35",
        irisManaged: true,
        retentionDays: 365,
        automaticInvoiceDeliveryIntegrated: false,
        notificationEmail: "motor@watercircles.no",
        insuranceAlternateNames: "watercircles",
        countryCode: "NO",
        externalId: "c83fa9ea-d099-47d8-94cd-d5c1c1da45f9",
        partnerPrimaryIds: [
          "59f17f2e975dec0001479e03",
          "5a4361e6853af600010f141b",
        ],
        partnerSecondaryIds: [
          "59e73abb56717ef6dd196e89",
          "59f190ac975dec0001491606",
          "59e73abb56717ef6dd196e72",
        ],
      },
      policyNumber: "100967802",
      coverage: {
        coverageLevel: null,
        deductible: 3000,
        deductiblePercentage: null,
        deductibleCurrency: "NOK",
        hasGlassCoverage: true,
      },
      insuranceObjectIdentifier: "DL39621",
      insuranceStart: "2025-01-01T00:00:00Z",
      insuranceEnd: "2025-12-31T23:59:59Z",
      customerCategory: "Personal",
      insuranceProduct: null,
    },
    images: [
      {
        id: "1f9d3577-fc30-484f-8ea5-c3a0031e9999",
        name: "7cfc3af4-f990-45ba-87ae-848a95d5c09d.jpg",
        imageType: "VehicleFront",
        checked: false,
        feature: null,
      },
      {
        id: "08af327f-5495-4f9a-8bd8-53d8171fa1bb",
        name: "8ae1f1e0-16fb-42ac-b041-9557f28c35f4.jpg",
        imageType: "Injury",
        checked: false,
        feature: "damage",
      },
      {
        id: "7e54fd66-239e-43fd-a3aa-d8b1eb4ae2f4",
        name: "6df24b01-af2f-44d5-a480-1bbf4d9cb0b2.jpg",
        imageType: "Misc",
        checked: false,
        feature: null,
      },
      {
        id: "7b2b17ea-fb61-4a8d-908c-f405b41a92c6",
        name: "7cfc3af4-f990-45ba-87ae-848a95d5c09d.jpg",
        imageType: "VehicleSide",
        checked: false,
        feature: null,
      },
    ],
    attachments: [
      {
        id: "9eab11ee-5354-4def-8aaf-1ade6b69d7f8",
        attachmentType: "InjuryReport",
        name: "6796f178-fc68-4e7d-ab60-2e11fcb96c8c.pdf",
      },
      {
        id: "11768913-a1f4-46a0-a263-941ecbaa006b",
        attachmentType: "Invoice",
        name: "faktura-7405261.pdf",
      },
    ],
    orderLines: [
      {
        id: "689b491441038c43f3b2a5f4",
        category: 15,
        articleNumber: "NOV",
        articlePrice: 600,
        discountPercent: 0,
        total: 600,
        sequenceNumber: 1,
        foundOEM: "",
        foundEurocode: "",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 15,
          newCategory: "Reparasjon",
          newArticleNumber: "NOV",
          newPrice: 600,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Linjen er godkjent",
            rule: "1",
          },
          newTotal: 600,
          foundOEM: null,
          foundEurocode: null,
        },
      },
    ],
    lastModified: "2025-08-12T14:43:29.555+00:00",
    invoice: {
      kidNumber: "74052614",
      receiverAccount: "007405261",
      totalSum: 750,
      adasOperator: null,
      updateKalibrering: false,
      shouldNotKalibrering: null,
      dueDate: "2025-09-11T00:00:00Z",
    },
    damageFormSignatureStatus: "SignedByCustomer",
    wear: "Low",
    tradeIn: false,
    lastCaseManager: {
      name: "Automatic Agent",
      id: "62a6e97a9f6b2b26787a0ff9",
      organizationName: "BELRON SOLUTIONS AS",
      caseWorkerRole: "CaseManager",
    },
    isDeductibleConfirmed: false,
    coverageStatus: "Approved",
    imagesStatus: "Approved",
    orderStatus: "Approved",
    invoiceStatus: "Approved",
    orderLinesStatus: "Approved",
    adasStatus: "MustBeChecked",
    approvedTotals: {
      approvedDate: "2025-08-12T14:43:29.528Z",
      totalBase: 600,
      totalVAT: 150,
      deductible: 0,
      totalSum: 750,
      insuranceVAT: 150,
      customerVAT: 0,
      priceComparison: {
        minimum: 10839.4,
        maximum: 17112.0,
        average: 12668.68,
        count: 45,
      },
    },
    claimId: "e5f05c3b-68bd-40de-ab87-b9e1a2ada085",

    // Activity Log Data
    activityLog: [
      {
        timestamp: "2025-01-08T09:30:00.000Z",
        actor: "System",
        action: "Case created automatically from workshop submission",
        type: "system_action",
        details: "Case BS304776 created for vehicle DL39621",
      },
      {
        timestamp: "2025-01-08T09:31:15.000Z",
        actor: "System",
        action: "Vehicle verification completed - Auto-approved",
        type: "status_change",
        details: "VIN NMTBZ20E70R135476 verified against vehicle registry",
      },
      {
        timestamp: "2025-01-08T10:15:30.000Z",
        actor: "Agent Larsen",
        action: "Insurance policy verified and approved",
        type: "status_change",
        details: "Policy coverage confirmed for glass replacement",
      },
      {
        timestamp: "2025-01-08T11:22:45.000Z",
        actor: "System",
        action: "Damage assessment images processed - Auto-warning",
        type: "status_change",
        details: "3 images uploaded, damage patterns detected",
      },
      {
        timestamp: "2025-01-08T14:45:10.000Z",
        actor: "Agent Larsen",
        action: "Parts and labor pricing approved",
        type: "status_change",
        details: "Total cost 750 NOK approved within guidelines",
      },
    ],

    publicComments: [
      {
        timestamp: "2025-01-08T10:30:00.000Z",
        author: "Agent Larsen",
        content:
          "Hei! Jeg har verifisert forsikringsdekningen. Alt ser bra ut og saken kan fortsette.",
        visibility: "public",
      },
      {
        timestamp: "2025-01-08T15:00:00.000Z",
        author: "RIIS BILGLASS",
        content:
          "Takk for rask behandling! Vi starter arbeidet i morgen tidlig.",
        visibility: "public",
      },
    ],

    internalNotes: [
      {
        timestamp: "2025-01-08T11:25:00.000Z",
        author: "Agent Larsen",
        content:
          "Skadebildene viser typisk steinsprut. Kunden har god forsikringshistorikk.",
        visibility: "internal",
      },
      {
        timestamp: "2025-01-08T14:50:00.000Z",
        author: "Agent Larsen",
        content:
          "Prisingen er innenfor normale rammer for Toyota Corolla frontrute. Godkjent.",
        visibility: "internal",
      },
    ],
  },
  {
    id: "689b491341038c43f3b2a5d3",
    caseNumber: "BS304777",
    vehicle: {
      vehicleLicenseNumber: "BN98765",
      brandName: "VOLVO",
      model: "XC90",
      firstRegistered: "2023-06-20T00:00:00Z",
      vehicleType: "PERSONBIL",
      vin: "YV1CZ91H5J2123456",
      color: "Blue",
      vehicleGroupType: null,
      isCommercialVan: false,
      vehicleGroupTypeName: null,
    },
    legalOwner: {
      name: "SARAH NIELSEN",
      phoneNumber: "95123456",
      address: "Storgata 15",
      postalCode: "0184",
      postalArea: "OSLO",
      email: "sarah.nielsen@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    caseWorker: {
      name: "Glassmester-Oslo",
      id: "656859a4ff02e9b608c6cdd6",
      organizationName: "GLASSMESTER OSLO",
      caseWorkerRole: "Workshop",
    },
    status: "ForApproval",
    dateOfIncident: "2025-08-05T00:00:00Z",
    jobExecutionDate: null,
    placeOfIncident: "Oslo centrum",
    cause: "Hagl",
    mileage: 45000,
    mileageUnit: "km",
    jobType: "Replace",
    multipleGlasses: ["SideWindow", "Sunroof"],
    contactPerson: null,
    contact: {
      name: "Sarah Nielsen",
      phoneNumber: "95123456",
      address: null,
      postalCode: null,
      postalArea: null,
      email: "sarah.nielsen@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    requiresVAT: true,
    registrationDate: "2025-08-11T10:15:22.123Z",
    caseDeductible: 2000,
    caseDeductibleCurrency: "NOK",
    deductiblePercentage: 0,
    isDeductiblePercentage: false,
    minDeductible: 2000,
    workshop: {
      name: "Glassmester Oslo Sentrum",
      organizationNumber: "987654321",
      organizationId: "641cc1568a43f5dc22fed98d",
      organizationMembership: {
        organizationNumber: "987 654 321",
        organizationId: "5a4361e6853af600010f141c",
        name: "GLASSMESTER OSLO",
        organizationType: "Organization",
      },
    },
    insuranceInformation: {
      id: null,
      insuranceOwner: {
        name: "Sarah Nielsen",
        phoneNumber: "95123456",
        address: null,
        postalCode: null,
        postalArea: null,
        email: "sarah.nielsen@email.com",
        organizationNumber: null,
        externalReference: null,
      },
      insuranceProvider: {
        id: "648b1fc6eef6a66f28bd8748",
        name: "IF SKADEFORSIKRING",
        organizationNumber: "915 495 487",
        key: "IF",
        settings: null,
        coverageResponseId: 36,
        status: "Enabled",
        universalId: "startid:36",
        irisManaged: true,
        retentionDays: 365,
        automaticInvoiceDeliveryIntegrated: true,
        notificationEmail: "motor@if.no",
        insuranceAlternateNames: "if",
        countryCode: "NO",
        externalId: "c83fa9ea-d099-47d8-94cd-d5c1c1da45fa",
        partnerPrimaryIds: ["59f17f2e975dec0001479e04"],
        partnerSecondaryIds: ["59e73abb56717ef6dd196e90"],
      },
      policyNumber: "IF-2023-12345",
      coverage: {
        coverageLevel: "Full",
        deductible: 2000,
        deductiblePercentage: null,
        deductibleCurrency: "NOK",
        hasGlassCoverage: true,
      },
      insuranceObjectIdentifier: "BN98765",
      insuranceStart: "2023-06-20T00:00:00Z",
      insuranceEnd: "2024-06-20T00:00:00Z",
      customerCategory: "Personal",
      insuranceProduct: "Full Coverage",
    },
    images: [
      {
        id: "2f9d3577-fc30-484f-8ea5-c3a0031e9998",
        name: "volvo-xc90-side-damage.jpg",
        imageType: "VehicleSide",
        checked: false,
        feature: null,
      },
      {
        id: "18af327f-5495-4f9a-8bd8-53d8171fa1bc",
        name: "volvo-xc90-roof-damage.jpg",
        imageType: "Injury",
        checked: false,
        feature: "damage",
      },
    ],
    attachments: [
      {
        id: "8eab11ee-5354-4def-8aaf-1ade6b69d7f9",
        attachmentType: "InjuryReport",
        name: "volvo-damage-report.pdf",
      },
    ],
    orderLines: [
      {
        id: "689b491441038c43f3b2a5f5",
        category: 10,
        articleNumber: "SW001",
        articlePrice: 5800,
        discountPercent: 0,
        total: 5800,
        sequenceNumber: 1,
        foundOEM: "VOL123",
        foundEurocode: "E001",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 10,
          newCategory: "Siderute",
          newArticleNumber: "SW001",
          newPrice: 5800,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Godkjent pris",
            rule: "2",
          },
          newTotal: 5800,
          foundOEM: "VOL123",
          foundEurocode: "E001",
        },
      },
      {
        id: "689b491441038c43f3b2a5f6",
        category: 12,
        articleNumber: "SR001",
        articlePrice: 15900,
        discountPercent: 0,
        total: 15900,
        sequenceNumber: 2,
        foundOEM: "VOL456",
        foundEurocode: "E002",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: false,
          newCategoryId: 12,
          newCategory: "Soltak",
          newArticleNumber: "SR001",
          newPrice: 15900,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Pending",
            text: "Venter på godkjenning - høy pris",
            rule: "3",
          },
          newTotal: 15900,
          foundOEM: "VOL456",
          foundEurocode: "E002",
        },
      },
    ],
    lastModified: "2025-08-11T10:15:22.123Z",
    invoice: {
      kidNumber: "74052615",
      receiverAccount: "007405262",
      totalSum: 27125,
      adasOperator: null,
      updateKalibrering: false,
      shouldNotKalibrering: null,
      dueDate: "2025-09-10T00:00:00Z",
    },
    damageFormSignatureStatus: "Pending",
    wear: "Medium",
    tradeIn: false,
    lastCaseManager: {
      name: "Manual Agent",
      id: "62a6e97a9f6b2b26787a0ffa",
      organizationName: "BELRON SOLUTIONS AS",
      caseWorkerRole: "CaseManager",
    },
    isDeductibleConfirmed: true,
    coverageStatus: "Approved",
    imagesStatus: "Approved",
    orderStatus: "Pending",
    invoiceStatus: "Pending",
    orderLinesStatus: "Pending",
    adasStatus: "NotRequired",
    approvedTotals: {
      approvedDate: null,
      totalBase: 21700,
      totalVAT: 5425,
      deductible: 2000,
      totalSum: 25125,
      insuranceVAT: 5425,
      customerVAT: 0,
    },
    claimId: "f5f05c3b-68bd-40de-ab87-b9e1a2ada086",
  },
  {
    id: "689b491341038c43f3b2a5d4",
    caseNumber: "BS304778",
    vehicle: {
      vehicleLicenseNumber: "VY54321",
      brandName: "BMW",
      model: "iX",
      firstRegistered: "2024-03-10T00:00:00Z",
      vehicleType: "PERSONBIL",
      vin: "WBYMZ1109M1234567",
      color: "Black",
      vehicleGroupType: null,
      isCommercialVan: false,
      vehicleGroupTypeName: null,
    },
    legalOwner: {
      name: "MIKAEL ROTNES",
      phoneNumber: "97654321",
      address: "Fjordveien 22",
      postalCode: "4006",
      postalArea: "STAVANGER",
      email: "mikael.rotnes@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    caseWorker: {
      name: "GlassPartner-Stavanger",
      id: "656859a4ff02e9b608c6cdd7",
      organizationName: "GLASSPARTNER STAVANGER",
      caseWorkerRole: "Workshop",
    },
    status: "Failed",
    dateOfIncident: "2025-08-07T00:00:00Z",
    jobExecutionDate: null,
    placeOfIncident: "Stavanger sentrum",
    cause: "Kollisjon",
    mileage: 12500,
    mileageUnit: "km",
    jobType: "Replace",
    multipleGlasses: [],
    contactPerson: null,
    contact: {
      name: "Mikael Rotnes",
      phoneNumber: "97654321",
      address: null,
      postalCode: null,
      postalArea: null,
      email: "mikael.rotnes@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    requiresVAT: true,
    registrationDate: "2025-08-10T08:45:12.456Z",
    caseDeductible: 4000,
    caseDeductibleCurrency: "NOK",
    deductiblePercentage: 0,
    isDeductiblePercentage: false,
    minDeductible: 4000,
    workshop: {
      name: "GlassPartner Stavanger Sentrum",
      organizationNumber: "987654322",
      organizationId: "641cc1568a43f5dc22fed98e",
      organizationMembership: {
        organizationNumber: "987 654 322",
        organizationId: "5a4361e6853af600010f141d",
        name: "GLASSPARTNER STAVANGER",
        organizationType: "Organization",
      },
    },
    insuranceInformation: {
      id: null,
      insuranceOwner: {
        name: "Mikael Rotnes",
        phoneNumber: "97654321",
        address: null,
        postalCode: null,
        postalArea: null,
        email: "mikael.rotnes@email.com",
        organizationNumber: null,
        externalReference: null,
      },
      insuranceProvider: {
        id: "648b1fc6eef6a66f28bd8749",
        name: "TRYG FORSIKRING",
        organizationNumber: "915 495 488",
        key: "TRYG",
        settings: null,
        coverageResponseId: 37,
        status: "Enabled",
        universalId: "startid:37",
        irisManaged: true,
        retentionDays: 365,
        automaticInvoiceDeliveryIntegrated: false,
        notificationEmail: "motor@tryg.no",
        insuranceAlternateNames: "tryg",
        countryCode: "NO",
        externalId: "c83fa9ea-d099-47d8-94cd-d5c1c1da45fb",
        partnerPrimaryIds: ["59f17f2e975dec0001479e05"],
        partnerSecondaryIds: ["59e73abb56717ef6dd196e91"],
      },
      policyNumber: "TR-2024-56789",
      coverage: {
        coverageLevel: "Premium",
        deductible: 4000,
        deductiblePercentage: null,
        deductibleCurrency: "NOK",
        hasGlassCoverage: true,
      },
      insuranceObjectIdentifier: "VY54321",
      insuranceStart: "2024-03-10T00:00:00Z",
      insuranceEnd: "2025-03-10T00:00:00Z",
      customerCategory: "Personal",
      insuranceProduct: "Premium Coverage",
    },
    images: [
      {
        id: "3f9d3577-fc30-484f-8ea5-c3a0031e9997",
        name: "bmw-ix-windshield-damage.jpg",
        imageType: "Injury",
        checked: false,
        feature: "damage",
      },
    ],
    attachments: [
      {
        id: "7eab11ee-5354-4def-8aaf-1ade6b69d7fa",
        attachmentType: "InjuryReport",
        name: "bmw-damage-report.pdf",
      },
    ],
    orderLines: [
      {
        id: "689b491441038c43f3b2a5f7",
        category: 1,
        articleNumber: "WS001",
        articlePrice: 18900,
        discountPercent: 0,
        total: 18900,
        sequenceNumber: 1,
        foundOEM: "BMW789",
        foundEurocode: "E003",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: false,
          newCategoryId: 1,
          newCategory: "Frontrute",
          newArticleNumber: "WS001",
          newPrice: 18900,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Declined",
            text: "Pris overskrider maksimum tillatt",
            rule: "4",
          },
          newTotal: 18900,
          foundOEM: "BMW789",
          foundEurocode: "E003",
        },
      },
      {
        id: "689b491441038c43f3b2a5f8",
        category: 15,
        articleNumber: "CAL001",
        articlePrice: 5500,
        discountPercent: 0,
        total: 5500,
        sequenceNumber: 2,
        foundOEM: "",
        foundEurocode: "",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 15,
          newCategory: "Kalibrering",
          newArticleNumber: "CAL001",
          newPrice: 5500,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Kalibrering godkjent",
            rule: "5",
          },
          newTotal: 5500,
          foundOEM: null,
          foundEurocode: null,
        },
      },
    ],
    lastModified: "2025-08-10T08:45:12.456Z",
    invoice: {
      kidNumber: "74052616",
      receiverAccount: "007405263",
      totalSum: 30500,
      adasOperator: "BMW Service",
      updateKalibrering: true,
      shouldNotKalibrering: false,
      dueDate: "2025-09-09T00:00:00Z",
    },
    damageFormSignatureStatus: "Missing",
    wear: "Low",
    tradeIn: false,
    lastCaseManager: {
      name: "Manual Agent",
      id: "62a6e97a9f6b2b26787a0ffb",
      organizationName: "BELRON SOLUTIONS AS",
      caseWorkerRole: "CaseManager",
    },
    isDeductibleConfirmed: false,
    coverageStatus: "Declined",
    imagesStatus: "Approved",
    orderStatus: "Declined",
    invoiceStatus: "Declined",
    orderLinesStatus: "Declined",
    adasStatus: "Required",
    approvedTotals: null,
    claimId: "g5f05c3b-68bd-40de-ab87-b9e1a2ada087",
  },
  {
    id: "689b491341038c43f3b2a5d5",
    caseNumber: "BS304779",
    vehicle: {
      vehicleLicenseNumber: "HK76543",
      brandName: "TOYOTA",
      model: "RAV4",
      firstRegistered: "2022-09-01T00:00:00Z",
      vehicleType: "PERSONBIL",
      vin: "JTMB1RFV7ND123456",
      color: "White",
      vehicleGroupType: null,
      isCommercialVan: false,
      vehicleGroupTypeName: null,
    },
    legalOwner: {
      name: "LISA MARTINEZ",
      phoneNumber: "99887766",
      address: "Rosenborgvegen 45",
      postalCode: "7030",
      postalArea: "TRONDHEIM",
      email: "lisa.martinez@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    caseWorker: {
      name: "AutoGlass-Trondheim",
      id: "656859a4ff02e9b608c6cdd8",
      organizationName: "AUTOGLASS TRONDHEIM",
      caseWorkerRole: "Workshop",
    },
    status: "AwaitingInvoice",
    dateOfIncident: "2025-08-02T00:00:00Z",
    jobExecutionDate: "2025-08-08T10:00:00Z",
    placeOfIncident: "E6 Trondheim",
    cause: "Steinsprut",
    mileage: 89000,
    mileageUnit: "km",
    jobType: "Replace",
    multipleGlasses: [],
    contactPerson: null,
    contact: {
      name: "Lisa Martinez",
      phoneNumber: "99887766",
      address: null,
      postalCode: null,
      postalArea: null,
      email: "lisa.martinez@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    requiresVAT: true,
    registrationDate: "2025-08-06T16:20:33.789Z",
    caseDeductible: 2000,
    caseDeductibleCurrency: "NOK",
    deductiblePercentage: 0,
    isDeductiblePercentage: false,
    minDeductible: 2000,
    workshop: {
      name: "AutoGlass Trondheim Øst",
      organizationNumber: "987654323",
      organizationId: "641cc1568a43f5dc22fed98f",
      organizationMembership: {
        organizationNumber: "987 654 323",
        organizationId: "5a4361e6853af600010f141e",
        name: "AUTOGLASS TRONDHEIM",
        organizationType: "Organization",
      },
    },
    insuranceInformation: {
      id: null,
      insuranceOwner: {
        name: "Lisa Martinez",
        phoneNumber: "99887766",
        address: null,
        postalCode: null,
        postalArea: null,
        email: "lisa.martinez@email.com",
        organizationNumber: null,
        externalReference: null,
      },
      insuranceProvider: {
        id: "648b1fc6eef6a66f28bd874a",
        name: "FREMTIND FORSIKRING",
        organizationNumber: "915 495 489",
        key: "FREMTIND",
        settings: null,
        coverageResponseId: 38,
        status: "Enabled",
        universalId: "startid:38",
        irisManaged: true,
        retentionDays: 365,
        automaticInvoiceDeliveryIntegrated: true,
        notificationEmail: "motor@fremtind.no",
        insuranceAlternateNames: "fremtind",
        countryCode: "NO",
        externalId: "c83fa9ea-d099-47d8-94cd-d5c1c1da45fc",
        partnerPrimaryIds: ["59f17f2e975dec0001479e06"],
        partnerSecondaryIds: ["59e73abb56717ef6dd196e92"],
      },
      policyNumber: "FR-2022-34567",
      coverage: {
        coverageLevel: "Standard",
        deductible: 2000,
        deductiblePercentage: null,
        deductibleCurrency: "NOK",
        hasGlassCoverage: true,
      },
      insuranceObjectIdentifier: "HK76543",
      insuranceStart: "2022-09-01T00:00:00Z",
      insuranceEnd: "2023-09-01T00:00:00Z",
      customerCategory: "Personal",
      insuranceProduct: "Standard Coverage",
    },
    images: [
      {
        id: "4f9d3577-fc30-484f-8ea5-c3a0031e9996",
        name: "toyota-rav4-before-repair.jpg",
        imageType: "Injury",
        checked: true,
        feature: "damage",
      },
      {
        id: "5f9d3577-fc30-484f-8ea5-c3a0031e9995",
        name: "toyota-rav4-after-repair.jpg",
        imageType: "AfterRepair",
        checked: true,
        feature: null,
      },
    ],
    attachments: [
      {
        id: "6eab11ee-5354-4def-8aaf-1ade6b69d7fb",
        attachmentType: "InjuryReport",
        name: "toyota-damage-report.pdf",
      },
      {
        id: "7eab11ee-5354-4def-8aaf-1ade6b69d7fc",
        attachmentType: "Invoice",
        name: "faktura-completed.pdf",
      },
    ],
    orderLines: [
      {
        id: "689b491441038c43f3b2a5f9",
        category: 1,
        articleNumber: "WS002",
        articlePrice: 9800,
        discountPercent: 0,
        total: 9800,
        sequenceNumber: 1,
        foundOEM: "TOY123",
        foundEurocode: "E004",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 1,
          newCategory: "Frontrute",
          newArticleNumber: "WS002",
          newPrice: 9800,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Standard Toyota frontrute",
            rule: "6",
          },
          newTotal: 9800,
          foundOEM: "TOY123",
          foundEurocode: "E004",
        },
      },
      {
        id: "689b491441038c43f3b2a5fa",
        category: 15,
        articleNumber: "CAL002",
        articlePrice: 4200,
        discountPercent: 0,
        total: 4200,
        sequenceNumber: 2,
        foundOEM: "",
        foundEurocode: "",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 15,
          newCategory: "Kalibrering",
          newArticleNumber: "CAL002",
          newPrice: 4200,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Toyota ADAS kalibrering",
            rule: "7",
          },
          newTotal: 4200,
          foundOEM: null,
          foundEurocode: null,
        },
      },
    ],
    lastModified: "2025-08-08T16:20:33.789Z",
    invoice: {
      kidNumber: "74052617",
      receiverAccount: "007405264",
      totalSum: 17500,
      adasOperator: "Toyota Service",
      updateKalibrering: true,
      shouldNotKalibrering: false,
      dueDate: "2025-09-08T00:00:00Z",
    },
    damageFormSignatureStatus: "SignedByCustomer",
    wear: "Medium",
    tradeIn: false,
    lastCaseManager: {
      name: "Automatic Agent",
      id: "62a6e97a9f6b2b26787a0ff9",
      organizationName: "BELRON SOLUTIONS AS",
      caseWorkerRole: "CaseManager",
    },
    isDeductibleConfirmed: true,
    coverageStatus: "Approved",
    imagesStatus: "Approved",
    orderStatus: "Approved",
    invoiceStatus: "Approved",
    orderLinesStatus: "Approved",
    adasStatus: "Completed",
    approvedTotals: {
      approvedDate: "2025-08-08T16:20:33.789Z",
      totalBase: 14000,
      totalVAT: 3500,
      deductible: 2000,
      totalSum: 15500,
      insuranceVAT: 3500,
      customerVAT: 0,
    },
    claimId: "h5f05c3b-68bd-40de-ab87-b9e1a2ada088",
  },
  {
    id: "689b491341038c43f3b2a5d6",
    caseNumber: "BS304780",
    vehicle: {
      vehicleLicenseNumber: "ZE23456",
      brandName: "VOLKSWAGEN",
      model: "ID.4",
      firstRegistered: "2023-11-15T00:00:00Z",
      vehicleType: "PERSONBIL",
      vin: "WVWZZZFY8NP123456",
      color: "Silver",
      vehicleGroupType: null,
      isCommercialVan: false,
      vehicleGroupTypeName: null,
    },
    legalOwner: {
      name: "DANIEL GOLAN",
      phoneNumber: "98765432",
      address: "Teknologiveien 12",
      postalCode: "3045",
      postalArea: "DRAMMEN",
      email: "daniel.golan@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    caseWorker: {
      name: "Glassmester-Drammen",
      id: "656859a4ff02e9b608c6cdd9",
      organizationName: "GLASSMESTER DRAMMEN",
      caseWorkerRole: "Workshop",
    },
    status: "OnHold",
    dateOfIncident: "2025-08-09T00:00:00Z",
    jobExecutionDate: null,
    placeOfIncident: "Drammen sentrum",
    cause: "Temperaturstress",
    mileage: 25000,
    mileageUnit: "km",
    jobType: "Replace",
    multipleGlasses: [],
    contactPerson: null,
    contact: {
      name: "Daniel Golan",
      phoneNumber: "98765432",
      address: null,
      postalCode: null,
      postalArea: null,
      email: "daniel.golan@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    requiresVAT: true,
    registrationDate: "2025-08-11T10:30:44.123Z",
    caseDeductible: 3000,
    caseDeductibleCurrency: "NOK",
    deductiblePercentage: 0,
    isDeductiblePercentage: false,
    minDeductible: 3000,
    workshop: {
      name: "Glassmester Drammen Vest",
      organizationNumber: "987654324",
      organizationId: "641cc1568a43f5dc22fed990",
      organizationMembership: {
        organizationNumber: "987 654 324",
        organizationId: "5a4361e6853af600010f141f",
        name: "GLASSMESTER DRAMMEN",
        organizationType: "Organization",
      },
    },
    insuranceInformation: {
      id: null,
      insuranceOwner: {
        name: "Daniel Golan",
        phoneNumber: "98765432",
        address: null,
        postalCode: null,
        postalArea: null,
        email: "daniel.golan@email.com",
        organizationNumber: null,
        externalReference: null,
      },
      insuranceProvider: {
        id: "648b1fc6eef6a66f28bd8747",
        name: "GJENSIDIGE FORSIKRING",
        organizationNumber: "915 495 490",
        key: "GJENSIDIGE",
        settings: null,
        coverageResponseId: 39,
        status: "Enabled",
        universalId: "startid:39",
        irisManaged: true,
        retentionDays: 365,
        automaticInvoiceDeliveryIntegrated: true,
        notificationEmail: "motor@gjensidige.no",
        insuranceAlternateNames: "gjensidige",
        countryCode: "NO",
        externalId: "c83fa9ea-d099-47d8-94cd-d5c1c1da45fd",
        partnerPrimaryIds: ["59f17f2e975dec0001479e07"],
        partnerSecondaryIds: ["59e73abb56717ef6dd196e93"],
      },
      policyNumber: "GJ-2023-90123",
      coverage: {
        coverageLevel: "Full",
        deductible: 3000,
        deductiblePercentage: null,
        deductibleCurrency: "NOK",
        hasGlassCoverage: true,
      },
      insuranceObjectIdentifier: "ZE23456",
      insuranceStart: "2023-11-15T00:00:00Z",
      insuranceEnd: "2024-11-15T00:00:00Z",
      customerCategory: "Personal",
      insuranceProduct: "Full Coverage",
    },
    images: [
      {
        id: "6f9d3577-fc30-484f-8ea5-c3a0031e9994",
        name: "vw-id4-crack-pattern.jpg",
        imageType: "Injury",
        checked: false,
        feature: "damage",
      },
    ],
    attachments: [
      {
        id: "8eab11ee-5354-4def-8aaf-1ade6b69d7fd",
        attachmentType: "InjuryReport",
        name: "vw-temperature-damage-report.pdf",
      },
    ],
    orderLines: [
      {
        id: "689b491441038c43f3b2a5fb",
        category: 1,
        articleNumber: "WS003",
        articlePrice: 14500,
        discountPercent: 0,
        total: 14500,
        sequenceNumber: 1,
        foundOEM: "VW123",
        foundEurocode: "E005",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: false,
          newCategoryId: 1,
          newCategory: "Frontrute",
          newArticleNumber: "WS003",
          newPrice: 14500,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Pending",
            text: "Venter på forsikringsgodkjenning",
            rule: "8",
          },
          newTotal: 14500,
          foundOEM: "VW123",
          foundEurocode: "E005",
        },
      },
      {
        id: "689b491441038c43f3b2a5fc",
        category: 15,
        articleNumber: "CAL003",
        articlePrice: 4800,
        discountPercent: 0,
        total: 4800,
        sequenceNumber: 2,
        foundOEM: "",
        foundEurocode: "",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: false,
          newCategoryId: 15,
          newCategory: "Kalibrering",
          newArticleNumber: "CAL003",
          newPrice: 4800,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Pending",
            text: "Avhenger av rutegodkjenning",
            rule: "9",
          },
          newTotal: 4800,
          foundOEM: null,
          foundEurocode: null,
        },
      },
    ],
    lastModified: "2025-08-11T10:30:44.123Z",
    invoice: {
      kidNumber: "74052618",
      receiverAccount: "007405265",
      totalSum: 24125,
      adasOperator: "VW Service",
      updateKalibrering: true,
      shouldNotKalibrering: false,
      dueDate: "2025-09-10T00:00:00Z",
    },
    damageFormSignatureStatus: "SignedByCustomer",
    wear: "Low",
    tradeIn: false,
    lastCaseManager: {
      name: "Manual Agent",
      id: "62a6e97a9f6b2b26787a0ffc",
      organizationName: "BELRON SOLUTIONS AS",
      caseWorkerRole: "CaseManager",
    },
    isDeductibleConfirmed: false,
    coverageStatus: "Pending",
    imagesStatus: "Warning",
    orderStatus: "Pending",
    invoiceStatus: "Pending",
    orderLinesStatus: "Pending",
    adasStatus: "Required",
    approvedTotals: null,
    claimId: "i5f05c3b-68bd-40de-ab87-b9e1a2ada089",
  },
  {
    id: "689b491341038c43f3b2a5d7",
    caseNumber: "BS308234",
    vehicle: {
      vehicleLicenseNumber: "EK12345",
      brandName: "MERCEDES-BENZ",
      model: "C-CLASS",
      firstRegistered: "2019-03-15T00:00:00Z",
      vehicleType: "PERSONBIL",
      vin: "WDD2059231N456789",
      color: "Svart",
      vehicleGroupType: null,
      isCommercialVan: false,
      vehicleGroupTypeName: null,
    },
    legalOwner: {
      name: "OLE HANSEN",
      phoneNumber: "92345678",
      address: "Storgata 15",
      postalCode: "0155",
      postalArea: "OSLO",
      email: "ole.hansen@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    caseWorker: {
      name: "Ekspert Glass",
      id: "656859a4ff02e9b608c6cdd6",
      organizationName: "NORSK BILGLASS AS",
      caseWorkerRole: "Workshop",
    },
    status: "PartsAndLabor",
    dateOfIncident: "2025-08-10T00:00:00Z",
    jobExecutionDate: "2025-08-20T00:00:00Z",
    placeOfIncident: "E6 ved Gardermoen",
    cause: "Steinsprut",
    mileage: 45200,
    mileageUnit: "km",
    jobType: "Replacement",
    multipleGlasses: ["Front windshield", "Side window"],
    contactPerson: null,
    contact: {
      name: "Ole Hansen",
      phoneNumber: "92345678",
      address: "Storgata 15",
      postalCode: "0155",
      postalArea: "OSLO",
      email: "ole.hansen@email.com",
      organizationNumber: null,
      externalReference: null,
    },
    insuranceInformation: {
      policyNumber: "POL789456123",
      insuranceStart: "2019-01-15T00:00:00Z",
      insuranceProvider: {
        name: "IF Skadeforsikring",
        id: "if-forsikring",
      },
      coverage: {
        coverageLevel: "Kasko",
        hasGlassCoverage: true,
        deductible: 3000,
        deductibleCurrency: "NOK",
        deductiblePercentage: null,
      },
      customerCategory: "Privatkunde",
      insuranceOwner: {
        name: "Ole Hansen",
        phoneNumber: "92345678",
        email: "ole.hansen@email.com",
      },
    },
    orderLines: [
      {
        id: "689b491441038c43f3b2a501",
        category: "Glass",
        articleNumber: "5382-65",
        articlePrice: 13970,
        discountPercent: 35,
        total: 9080.5,
        sequenceNumber: 1,
        foundOEM: "Mercedes-Benz OEM",
        foundEurocode: "E1",
        savings: 4889.5,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 1,
          newCategory: "Glass",
          newArticleNumber: "5382-65",
          newPrice: 13970,
          newDiscount: 35,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Linjen er godkjent",
            rule: "1",
          },
          newTotal: 9080.5,
          foundOEM: "Mercedes-Benz OEM",
          foundEurocode: "E1",
        },
      },
      {
        id: "689b491441038c43f3b2a502",
        category: "Tilbehør",
        articleNumber: "F201",
        articlePrice: 310,
        discountPercent: 0,
        total: 310,
        sequenceNumber: 2,
        foundOEM: "",
        foundEurocode: "",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 2,
          newCategory: "Tilbehør",
          newArticleNumber: "F201",
          newPrice: 310,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Linjen er godkjent",
            rule: "1",
          },
          newTotal: 310,
          foundOEM: null,
          foundEurocode: null,
        },
      },
      {
        id: "689b491441038c43f3b2a503",
        category: "Arbeid monteringspris",
        articleNumber: "M010",
        articlePrice: 1750,
        discountPercent: 10,
        total: 1575,
        sequenceNumber: 3,
        foundOEM: "",
        foundEurocode: "",
        savings: 175,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 3,
          newCategory: "Arbeid monteringspris",
          newArticleNumber: "M010",
          newPrice: 1750,
          newDiscount: 10,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Linjen er godkjent",
            rule: "1",
          },
          newTotal: 1575,
          foundOEM: null,
          foundEurocode: null,
        },
      },
      {
        id: "689b491441038c43f3b2a504",
        category: "Rutelim",
        articleNumber: "2K",
        articlePrice: 847,
        discountPercent: 30,
        total: 592.9,
        sequenceNumber: 4,
        foundOEM: "",
        foundEurocode: "",
        savings: 254.1,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 4,
          newCategory: "Rutelim",
          newArticleNumber: "2K",
          newPrice: 847,
          newDiscount: 30,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Linjen er godkjent",
            rule: "1",
          },
          newTotal: 592.9,
          foundOEM: null,
          foundEurocode: null,
        },
      },
      {
        id: "689b491441038c43f3b2a505",
        category: "Verkstedmateriell",
        articleNumber: "VM",
        articlePrice: 150,
        discountPercent: 0,
        total: 150,
        sequenceNumber: 5,
        foundOEM: "",
        foundEurocode: "",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 5,
          newCategory: "Verkstedmateriell",
          newArticleNumber: "VM",
          newPrice: 150,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Linjen er godkjent",
            rule: "1",
          },
          newTotal: 150,
          foundOEM: null,
          foundEurocode: null,
        },
      },
      {
        id: "689b491441038c43f3b2a506",
        category: "Sensor / Sensorgel",
        articleNumber: "13360163",
        articlePrice: 395,
        discountPercent: 25,
        total: 296.25,
        sequenceNumber: 6,
        foundOEM: "OEM Part",
        foundEurocode: "",
        savings: 98.75,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 6,
          newCategory: "Sensor / Sensorgel",
          newArticleNumber: "13360163",
          newPrice: 395,
          newDiscount: 25,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Linjen er godkjent",
            rule: "1",
          },
          newTotal: 296.25,
          foundOEM: "OEM Part",
          foundEurocode: null,
        },
      },
      {
        id: "689b491441038c43f3b2a507",
        category: "Tilbehør",
        articleNumber: "AVSTANDSKLOSS25",
        articlePrice: 240,
        discountPercent: 25,
        total: 180,
        sequenceNumber: 7,
        foundOEM: "",
        foundEurocode: "",
        savings: 60,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 2,
          newCategory: "Tilbehør",
          newArticleNumber: "AVSTANDSKLOSS25",
          newPrice: 240,
          newDiscount: 25,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Linjen er godkjent",
            rule: "1",
          },
          newTotal: 180,
          foundOEM: null,
          foundEurocode: null,
        },
      },
      {
        id: "689b491441038c43f3b2a508",
        category: "Statisk Kalibrering",
        articleNumber: "KALIBS",
        articlePrice: 900,
        discountPercent: 0,
        total: 900,
        sequenceNumber: 8,
        foundOEM: "",
        foundEurocode: "",
        savings: 0,
        quantity: 1,
        priceAgreementResponse: {
          isSuccessfull: true,
          newCategoryId: 7,
          newCategory: "Statisk Kalibrering",
          newArticleNumber: "KALIBS",
          newPrice: 900,
          newDiscount: 0,
          newQuantity: 1,
          comment: {
            status: "Approved",
            text: "Linjen er godkjent",
            rule: "1",
          },
          newTotal: 900,
          foundOEM: null,
          foundEurocode: null,
        },
      },
    ],
    lastModified: "2025-08-15T10:30:00.000+00:00",
    invoice: {
      kidNumber: "85739264",
      receiverAccount: "007485739",
      totalSum: 13084.65,
      adasOperator: "Kalibreringstekniker",
      updateKalibrering: true,
      shouldNotKalibrering: false,
      dueDate: "2025-09-15T00:00:00Z",
    },
    damageFormSignatureStatus: "SignedByCustomer",
    wear: "Medium",
    tradeIn: false,
    lastCaseManager: {
      name: "Smart Agent",
      id: "62a6e97a9f6b2b26787a0ff8",
      organizationName: "NORSK BILGLASS AS",
      caseWorkerRole: "CaseManager",
    },
    isDeductibleConfirmed: true,
    coverageStatus: "Approved",
    imagesStatus: "Approved",
    orderStatus: "Approved",
    invoiceStatus: "Approved",
    orderLinesStatus: "Approved",
    adasStatus: "Required",
    requiresVAT: true,
    approvedTotals: {
      approvedDate: "2025-08-15T10:30:00.000Z",
      totalBase: 13084.65,
      totalVAT: 3271.16,
      deductible: 3000.0,
      totalSum: 16355.81,
      insuranceVAT: 2521.16,
      customerVAT: 750.0,
      amountToInsurance: 10084.65,
      // Price comparison data
      priceComparison: {
        totalPrice: 13084.65,
        minimum: 9017.2,
        maximum: 21875.17,
        count: 387,
        average: 13018.25,
      },
    },
    claimId: "f6g07d4c-79ce-41ef-bc98-c0f2b3beb190",

    // Activity Log Data
    activityLog: [
      {
        timestamp: "2025-08-10T08:00:00.000Z",
        actor: "System",
        action: "Case created from workshop submission",
        type: "system_action",
        details: "Case BS308234 created for vehicle EK12345",
      },
      {
        timestamp: "2025-08-10T08:01:00.000Z",
        actor: "System",
        action: "Vehicle verification completed - Auto-approved",
        type: "status_change",
        details: "VIN WDD2059231N456789 verified against vehicle registry",
      },
      {
        timestamp: "2025-08-10T08:15:00.000Z",
        actor: "Agent Sarah",
        action: "Insurance coverage verified",
        type: "status_change",
        details: "IF Skadeforsikring policy confirmed with glass coverage",
      },
      {
        timestamp: "2025-08-10T09:30:00.000Z",
        actor: "Workshop",
        action: "Damage assessment completed",
        type: "status_change",
        details:
          "Front windshield replacement required due to extensive damage",
      },
      {
        timestamp: "2025-08-10T10:45:00.000Z",
        actor: "System",
        action: "Parts & Labor pricing approved automatically",
        type: "status_change",
        details: "All 8 order lines approved within price guidelines",
      },
      {
        timestamp: "2025-08-10T11:00:00.000Z",
        actor: "Customer",
        action: "Digital signature completed",
        type: "system_action",
        details: "Damage form signed electronically by Ole Hansen",
      },
    ],

    publicComments: [
      {
        timestamp: "2025-08-10T10:00:00.000Z",
        author: "Workshop",
        text: "Steinsprut på frontrute, må skiftes. ADAS kalibrering påkrevd.",
      },
      {
        timestamp: "2025-08-10T14:30:00.000Z",
        author: "Agent Sarah",
        text: "Alle deler godkjent. Kan bestilles og monteres.",
      },
    ],

    internalNotes: [
      {
        timestamp: "2025-08-10T08:30:00.000Z",
        author: "Agent Sarah",
        text: "Mercedes C-klasse 2019 - premium glass required. Customer has full kasko.",
      },
      {
        timestamp: "2025-08-10T11:15:00.000Z",
        author: "Agent Sarah",
        text: "ADAS kalibrering må utføres av sertifisert tekniker. Verksted bekreftet kompetanse.",
      },
    ],
  },
];

export const getStatusCounts = () => {
  const counts = {
    "For Approval": 0,
    "Invoice Control": 0,
    Failed: 0,
    "On Hold": 0,
  };

  sampleCases.forEach((caseItem) => {
    if (caseItem.status === "ReadyForApproval") {
      counts["For Approval"]++;
    } else if (
      caseItem.status === "InvoiceApproved" ||
      caseItem.status === "InvoiceControl"
    ) {
      counts["Invoice Control"]++;
    } else if (caseItem.status === "Failed") {
      counts["Failed"]++;
    } else if (caseItem.status === "OnHold") {
      counts["On Hold"]++;
    } else {
      // Default category for any other statuses
      counts["For Approval"]++;
    }
  });

  return counts;
};

export const searchCases = (query) => {
  if (!query) return sampleCases;

  const lowercaseQuery = query.toLowerCase();
  return sampleCases.filter(
    (caseItem) =>
      caseItem.vehicle?.vehicleLicenseNumber
        ?.toLowerCase()
        .includes(lowercaseQuery) ||
      caseItem.caseNumber?.toLowerCase().includes(lowercaseQuery) ||
      caseItem.insuranceInformation?.insuranceProvider?.name
        ?.toLowerCase()
        .includes(lowercaseQuery) ||
      caseItem.vehicle?.brandName?.toLowerCase().includes(lowercaseQuery) ||
      caseItem.vehicle?.model?.toLowerCase().includes(lowercaseQuery) ||
      caseItem.cause?.toLowerCase().includes(lowercaseQuery) ||
      caseItem.status?.toLowerCase().includes(lowercaseQuery) ||
      caseItem.vehicle?.vin?.toLowerCase().includes(lowercaseQuery) ||
      caseItem.legalOwner?.name?.toLowerCase().includes(lowercaseQuery) ||
      caseItem.contact?.name?.toLowerCase().includes(lowercaseQuery) ||
      caseItem.workshop?.name?.toLowerCase().includes(lowercaseQuery) ||
      // Search in order lines
      (caseItem.orderLines &&
        caseItem.orderLines.some(
          (orderLine) =>
            orderLine.priceAgreementResponse?.newCategory
              ?.toLowerCase()
              .includes(lowercaseQuery) ||
            orderLine.articleNumber?.toLowerCase().includes(lowercaseQuery)
        ))
  );
};

export const getCaseById = (id) => {
  return sampleCases.find((caseItem) => caseItem.id === id);
};

export const getCaseByCaseNumber = (caseNumber) => {
  return sampleCases.find((caseItem) => caseItem.caseNumber === caseNumber);
};
